# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

forward_backward <- function(logEmiss, Dist, a, f) {
    .Call('_Fantasio_forward_backward', PACKAGE = 'Fantasio', logEmiss, Dist, a, f)
}

logLikelihood <- function(logEmiss, Dist, a, f) {
    .Call('_Fantasio_logLikelihood', PACKAGE = 'Fantasio', logEmiss, Dist, a, f)
}

logLikelihood_gradient <- function(logEmiss, Dist, a, f) {
    .Call('_Fantasio_logLikelihood_gradient', PACKAGE = 'Fantasio', logEmiss, Dist, a, f)
}

logEmiss <- function(Y1, Y2, logFreq, epsilon) {
    .Call('_Fantasio_logEmiss', PACKAGE = 'Fantasio', Y1, Y2, logFreq, epsilon)
}

m4_logEmiss <- function(p_A, p, map, epsilon) {
    .Call('_Fantasio_m4_logEmiss', PACKAGE = 'Fantasio', p_A, p, map, epsilon)
}

simu_geno <- function(S, Freq) {
    .Call('_Fantasio_simu_geno', PACKAGE = 'Fantasio', S, Freq)
}

